#----------------------------------------------------------------
# Travis-CI configuration for Bioconductor packages
#
# REFERENCES:
# * Travis CI: https://travis-ci.org/
# * tutorial: https://docs.travis-ci.com/user/languages/r
# * see also: https://blog.rstudio.org/2016/03/09/r-on-travis-ci/
# * covr: https://github.com/jimhester/covr
# * Coveralls: https://coveralls.io/
#
# Validate your .travis.yml file at http://lint.travis-ci.org/
#----------------------------------------------------------------

language: r
sudo: required
dist: trusty
cache: packages

before_install:
  - sudo Rscript -e 'update.packages(ask = FALSE)'
  - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
  - tlmgr install ucs index inputenc

## BiocCheck
bioc_packages:
  - impute
  - preprocessCore
  - GO.db
  - AnnotationDbi
