# Project information
site_name: 'eclust'
site_description: 'A short description of my project'
site_author: 'Sahir Rai Bhatnagar'
site_url: 'https://sahirbhatnagar.github.io/eclust'

# Repository
repo_name: 'eclust'
repo_url: 'https://github.com/sahirbhatnagar/eclust'

# Copyright
copyright: 'Copyright &copy; 2017 Sahir Rai Bhatnagar'

# Documentation and theme
theme: 'material'

extra_javascript:
  - 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML'

# Options
extra:
  logo: 'images/dte1.png'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/sahirbhatnagar'
    - type: 'twitter'
      link: 'https://twitter.com/syfi_24'

# Google Analytics
#google_analytics:
#  - 'UA-XXXXXXXX-X'
#  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite(guess_lang=true)
  - footnotes
  - meta
  - toc(permalink=true)


# Page tree
pages:
  - Home: index.md
  - Installation: installation.md
  - Data: data.md
  - Package Functions: overview.md
  - Real Data Analysis: rda.md
  - Simulations: simulation.md
  - Heatmaps: plots.md
#  - Extensions:
#    - Admonition: extensions/admonition.md
#    - CodeHilite: extensions/codehilite.md
#    - Footnotes: extensions/footnotes.md
#    - Permalinks: extensions/permalinks.md
#    - PyMdown: extensions/pymdown.md
#  - Specimen: specimen.md
#  - Customization: customization.md
#  - Release notes: release-notes.md
#  - Contributing: contributing.md
#  - License: license.md
